package com.example.gymfitbackend.pojo;

public class User {
    private int id; // Make it the autogenerated field in database
    private String username; // Save the username as is
    private String password; // Hash the password and save it (sha256 hash and salt it before storing).
    private boolean is_admin; // only allow if the user is admin
    private boolean is_active; // only allow if the user is active
    private boolean payment_due; //tick if the payment is due
    private String client_type; // choices between "Gym", "Yoga", "Cardio", "Cardio + Gym" and so on.
}
